# image will be published to ghcr.io/<user>/<name>
name: silverblue-alexis
# description will be included in the image's metadata
description: My personal developer workstation image, with everything I need.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
    install:
      - firmware-manager
      - fish
      - stow
      - emacs
      - chkrootkit
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gdm
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark

        # GNOME Apps
        - org.gnome.Characters
        - org.gnome.Snapshot
        - org.gnome.Calculator
        - org.gnome.Evince
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.font-viewer
        - io.bassi.Amberol

        # Terminal
        - org.gnome.Ptyxis.Devel
    user:
      install:
        # Utility Applications
        - com.belmoussaoui.Authenticator
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - com.github.finefindus.eyedropper
        - me.kozec.syncthingtk

        # Office/Productivity
        - com.calibre_ebook.calibre
        - org.libreoffice.LibreOffice
        - org.blender.Blender
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - io.gitlab.librewolf-community

        # Communication
        - com.discordapp.Discord
        - org.signal.Signal
        - ch.protonmail.protonmail-bridge

        # Games
        - com.valvesoftware.Steam
        - io.github.garglk.Gargoyle

        # Development
        - com.google.AndroidStudio
  - type: gnome-extensions
    install:
      - Forge
      - Privacy Quick Settings
      - Search Light
      - 1708 # Transparent Top Bar by zhanghai
      - User Themes
      - Vitals
      - 5177 # V-Shell (Vertical Workspaces)
      - Custom Accent Colors
      - GSConnect
      - 6721 # ESP (Extensions Search Provider)
      - 6730 # WSP (Windows Search Provider)
  - type: gschema-overrides
    include:
      - zz1-alexis.gschema.override

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
      google-fonts:
        - JetBrains Mono
        - Cardo
        - Lato

  - type: systemd
    system:
      enabled:
        - system76-firmware-daemon
    user:
      enabled:
        - emacs

  - type: script
    snippets:
      - "flatpak override --system --filesystem=host-os:ro --nodevice=all"
      - "echo 'HOMEBREW_NO_ANALYTICS=1\n' >> /usr/etc/environment"
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

